#!/usr/bin/fish
# Resource
# https://bbs.archlinux.org/viewtopic.php?id=224560
echo "Power save value: " && cat /sys/module/snd_hda_intel/parameters/power_save # might be 1
echo "Power Save Controller Value: " && cat /sys/module/snd_hda_intel/parameters/power_save_controller # might be Y

echo 0 > /sys/module/snd_hda_intel/parameters/power_save # writing 0
echo N > /sys/module/snd_hda_intel/parameters/power_save_controller # writing N
echo "..."
echo "Rewrote values..."
echo "Power save value: " && cat /sys/module/snd_hda_intel/parameters/power_save # should be 0
echo "Power Save Controller Value: " && cat /sys/module/snd_hda_intel/parameters/power_save_controller # should be N
